# permissions for end users to view argocdusers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocduser-viewer-role
rules:
- apiGroups:
  - argocd.snappcloud.io
  resources:
  - argocdusers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - argocd.snappcloud.io
  resources:
  - argocdusers/status
  verbs:
  - get
