# permissions for end users to edit argocdusers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocduser-editor-role
rules:
- apiGroups:
  - argocduser.snappcloud.io
  resources:
  - argocdusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - argocduser.snappcloud.io
  resources:
  - argocdusers/status
  verbs:
  - get
